--Portalgun resource download list

CreateConVar("portal_bullet", "1", true, "Allow shooting through the portal.")

resource.AddFile("models/weapons/portalgun/w_portalgun_hl2.mdl")
resource.AddFile("models/weapons/portalgun/v_portalgun.mdl")
resource.AddFile("models/blackops/portal.mdl")
resource.AddFile("models/blackops/portal_sides.mdl")

resource.AddFile("particles/particles_manifest.txt")
resource.AddFile("particles/portal_projectile.pcf")
resource.AddFile("particles/portalgun.pcf")
resource.AddFile("particles/portals.pcf")
resource.AddFile("particles/cleansers.pcf")
resource.AddFile("particles/wip_muzzle.pcf")
resource.AddFile("particles/portal_beta_particles2.pcf")

resource.AddFile("materials/sprites/blborder.vmt")
resource.AddFile("materials/sprites/blueborder.vmt")
resource.AddFile("materials/sprites/blueNoDraw.png")
resource.AddFile("materials/sprites/orangeNoDraw.png")
resource.AddFile("materials/sprites/noblue.vmt")
resource.AddFile("materials/sprites/nored.vmt")
resource.AddFile("materials/sprites/ogborder.vmt")
resource.AddFile("materials/sprites/redborder.vmt")

resource.AddFile("materials/models/fakeportal_ring_blue.vmt")
resource.AddFile("materials/models/fakeportal_ring_red.vmt")
resource.AddFile("materials/models/portalat1.vmt")
resource.AddFile("materials/models/portalat2.vmt")
resource.AddFile("materials/models/portalblue.vmt")
resource.AddFile("materials/models/portalred.vmt")
resource.AddFile("materials/models/portalpb1.vmt")
resource.AddFile("materials/models/portalpb2.vmt")

resource.AddFile("materials/models/weapons/camera.vmt")
resource.AddFile("materials/models/weapons/v_hands.vmt")
resource.AddFile("materials/models/weapons/v_portalgun.vtf")

resource.AddFile("materials/models/weapons/v_models/v_portalgun/potatos_vmodel.vmt")
resource.AddFile("materials/models/weapons/v_models/v_portalgun/v_hands.vmt")
resource.AddFile("materials/models/weapons/v_models/v_portalgun/v_portalgun.vmt")
resource.AddFile("materials/models/weapons/v_models/v_portalgun/v_portalgun_blue.vmt")
resource.AddFile("materials/models/weapons/v_models/v_portalgun/v_portalgun_glass.vmt")
resource.AddFile("materials/models/weapons/v_models/v_portalgun/v_portalgun_orange.vmt")
resource.AddFile("materials/models/weapons/v_models/v_portalgun/v_portalgun2.vmt")

resource.AddFile("materials/models/weapons/w_models/portalgun/w_portalgun.vmt")
resource.AddFile("materials/models/weapons/w_models/portalgun/w_portalgun_blue.vmt")
resource.AddFile("materials/models/weapons/w_models/portalgun/w_portalgun_orange.vmt")
resource.AddFile("materials/models/weapons/w_models/portalgun/w_portalgun_potatos.vmt")

resource.AddFile("materials/vgui/entities/weapon_portalgun.vmt")
resource.AddFile("materials/vgui/entities/weapon_portalgun.vtf")

resource.AddFile("materials/vgui/portalgun/lastFired.png")
resource.AddFile("materials/vgui/portalgun/leftEmpty.png")
resource.AddFile("materials/vgui/portalgun/leftFull.png")
resource.AddFile("materials/vgui/portalgun/rightEmpty.png")
resource.AddFile("materials/vgui/portalgun/rightFull.png")

resource.AddFile("materials/weapons/portalgun_inventory.vmt")

resource.AddFile("scripts/game_sounds_player_portal.txt")
resource.AddFile("scripts/game_sounds_portal.txt")
resource.AddFile("scripts/game_sounds_weapons_portal.txt")

resource.AddFile("sound/weapons/portalgun/portal_fizzle1.wav")
resource.AddFile("sound/weapons/portalgun/portal_fizzle2.wav")
resource.AddFile("sound/weapons/portalgun/portalgun_shoot_blue1.wav")
resource.AddFile("sound/weapons/portalgun/portalgun_shoot_red1.wav")
resource.AddFile("sound/weapons/portalgun/portal_ambient_loop1.wav")
resource.AddFile("sound/weapons/portalgun/portal_close1.wav")
resource.AddFile("sound/weapons/portalgun/portal_close2.wav")
resource.AddFile("sound/weapons/portalgun/portal_invalid_surface3.wav")
resource.AddFile("sound/weapons/portalgun/portal_open1.wav")
resource.AddFile("sound/weapons/portalgun/portal_open3.wav")
